### ISSUE TITLE
500 Error Authorization

### ISSUE THREAD

**Issue by sunuiyum** [spotify/web-api#101]
I'm trying to get a token to authorize my web app using the spotipy Python library, and I'm getting thrown a 500 Error. 

```Error in event handler for (unknown): TypeError: Cannot read property 'user' of null
    at Object.<anonymous> (chrome-extension://bmnlcjabgnpnenekpadlanbbkooimhnj/src/js/build/all.js:9:6697)
    at k (chrome-extension://bmnlcjabgnpnenekpadlanbbkooimhnj/src/js/lib/jquery-1.8.1.min.js:2:16934)
    at Object.l.fireWith (chrome-extension://bmnlcjabgnpnenekpadlanbbkooimhnj/src/js/lib/jquery-1.8.1.min.js:2:17721)
    at Object.l.fire [as resolve] (chrome-extension://bmnlcjabgnpnenekpadlanbbkooimhnj/src/js/lib/jquery-1.8.1.min.js:2:17758)
    at chrome-extension://bmnlcjabgnpnenekpadlanbbkooimhnj/src/js/build/all.js:1:1516
    at Object.success (chrome-extension://bmnlcjabgnpnenekpadlanbbkooimhnj/forge/all.js:8751:4)
    at Object.internal.priv.receive (chrome-extension://bmnlcjabgnpnenekpadlanbbkooimhnj/forge/all.js:8504:29)
    at chrome-extension://bmnlcjabgnpnenekpadlanbbkooimhnj/forge/all.js:9809:16handler @ extensions::uncaught_exception_handler:8```

```Failed to load resource: the server responded with a status of 500 (Internal Server Error)```

**Comment by thelinmichael** [comment]
Thanks for reporting this @sunuiyum! 

I see two issues here,

- Retrieving a 500 server error when authenticated is obviously severe and should never happen.
- The [Spotipy](https://github.com/plamere/spotipy) library should handle a server error better than this.

This issue tracker is appropriate to handle the first of these issues since Spotipy is just another client utilising the Web API. To be able to troubleshoot this issue it'd be very helpful if you could provide more information about the request that returned the server error. 

Can you reproduce it every time? If so, when does it occur?

Thanks again!

**Comment by thelinmichael** [comment]
Early morning, I see you've closed it yourself so I'm going to assume that this wasn't reproducible. Please let us know if it occurs again.
