### ISSUE TITLE
Exception Raised 400

### ISSUE THREAD

**Issue by SheebanWasi** [spotify/web-api#1563]
Hey, 
As I am using Spotify API to add youtube liked songs in my private library playlist.

- I am creating a playlist
- Adding youtube liked songs to the playlist

Traceback (most recent call last):
  File "spotify_youtube.py", line 168, in <module>
    cp.add_song_to_playlist()
  File "spotify_youtube.py", line 160, in add_song_to_playlist
    raise ResponseException(response.status_code)
exceptions.ResponseException: Response gave status code 400

The codes for the following functions are the following:

`def add_song_to_playlist(self):
        # populate dictionary with our liked songs
        self.get_liked_videos()
        # collect all of uri
        uris = [info["spotify_uri"]
                for song, info in self.all_song_info.items()]
        # create a new playlist
        playlist_id = self.create_playlist()
        # add all songs into new playlist
        request_data = json.dumps(uris)
        query = "https://api.spotify.com/v1/playlists/{}/tracks".format(
            playlist_id)
        response = requests.post(
            query,
            data=request_data,
            headers={
                "Content-Type": "application/json",
                "Authorization": "Bearer {}".format(spotify_token)
            }
        )
        # check for valid response status
        response_json = response.json()
        return response_json`

Can you help why it's throwing this error

Issue found on February 19th 2015.

#### Endpoint(s):
* `GET /v1/users/{user_id}`

#### Scope(s):
* None (application is not using authentication)

#### Steps to reproduce:
1. Open the API Console
2. Call the `get-users-profile` endpoint with `user_id` `%5E`

#### Expected behaviour:
A public user object as described on `https://developer.spotify.com/web-api/object-model/#user-object-public`.

#### Actual behaviour:
500 Server Error (consistently)

**Comment by ng1905** [comment]
Are you filing a bug report? HTTP Status 400 is a bad request, so you probably want to check the data you're sending.
